name: astra
description: >
  Astra is Shelf web server adapter and application framework.
version: 1.0.0-dev.138
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/packages/astra
repository: https://github.com/ykmnkmi/astra.dart/tree/master/packages/astra

environment:
  sdk: ">=2.18.0 <3.0.0"

executables:
  astra: astra

dependencies:
  collection: ^1.17.0
  http: ^0.13.5
  http_parser: ^4.0.2
  meta: ^1.8.0
  shelf: ^1.4.0
  stack_trace: ^1.11.0
  stream_channel: ^2.1.1

dev_dependencies:
  astra_cli: ^1.0.0-dev.0
  lints: ^2.0.1
  test: ^1.22.0
