name: astra
description: >
  Astra is Shelf web server adapter and application framework.
version: 1.0.0-dev.145
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/packages/astra
repository: https://github.com/ykmnkmi/astra.dart/tree/master/packages/astra

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  http: ^1.0.0
  http_parser: ^4.0.2
  meta: ^1.9.1
  shelf: ^1.4.1
  stack_trace: ^1.11.0
  stream_channel: ^2.1.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
