name: example
description: A Shelf based Astra application.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  astra: ^1.0.0-dev.105

dev_dependencies:
  lints: ^2.0.0

dependency_overrides:
  astra:
    path: ../
