include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_dynamic_calls: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_print: true
    avoid_void_async: true
    combinators_ordering: true
    directives_ordering: true
    library_prefixes: false
    prefer_single_quotes: true
    # public_member_api_docs: true
    unnecessary_final: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_super_parameters: true
