include: package:lints/recommended.yaml

analyzer:
  # exclude:
  #   - example/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: true
    void_checks: false
