name: astra
description: Astra is a Shelf web server with multi-threaded support and hot reload/restart. Inspired by uvicorn.
version: 1.0.0-dev.126
homepage: https://github.com/ykmnkmi/astra.dart
repository: https://github.com/ykmnkmi/astra.dart

environment:
  sdk: '>=2.18.0 <3.0.0'

executables:
  astra: astra

dependencies:
  analyzer: ^5.2.0
  args: ^2.3.1
  collection: ^1.17.0
  http: ^0.13.5
  http2: ^2.0.1
  http_parser: ^4.0.2
  logging: ^1.1.0
  meta: ^1.8.0
  path: ^1.8.2
  shelf: ^1.4.0
  stack_trace: ^1.11.0
  stream_channel: ^2.1.1
  stream_transform: ^2.0.1
  vm_service: ^9.4.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.2
  build_version: ^2.1.1
  lints: ^2.0.1
  test: ^1.21.7
