name: astra
description: Astra is a Shelf web server implementation with multi-threaded support and hot reload.
version: 1.0.0-dev.79
homepage: https://github.com/ykmnkmi/astra.dart
repository: https://github.com/ykmnkmi/astra.dart

environment:
  sdk: '>=2.16.0 <3.0.0'

executables:
  astra: astra

dependencies:
  args: ^2.3.0
  meta: ^1.7.0
  path: ^1.8.0
  shelf: ^1.2.0
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0
  vm_service: ^8.2.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.0
