name: astra
description: A Shelf based web server framework.
version: 1.0.0-dev.70
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

executables:
  astra: astra

dependencies:
  args: ^2.3.0
  meta: ^1.7.0
  shelf: ^1.2.0
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0
  vm_service: ^8.2.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
