name: astra
description: A Shelf based web server framework.
version: 1.0.0-dev.65
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^3.3.1
  args: ^2.3.0
  collection: ^1.16.0
  http_parser: ^4.0.0
  logging: ^1.0.2
  meta: ^1.7.0
  shelf: ^1.2.0
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0
  vm_service: ^8.2.0
  yaml: ^3.1.0

dev_dependencies:
  http: ^0.13.4
  l: ^3.1.0
  lints: ^1.0.1
  path: ^1.8.1
  test: ^1.20.1
