name: astra
description: A simple web server framework based on starlette.
version: 1.0.0-dev.28
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  http: ^0.13.3
  http_multi_server: ^3.0.1
  http_parser: ^4.0.0
  meta: ^1.4.0
  mime: ^1.0.0
  path: ^1.8.0
  stack_trace: ^1.10.0

dev_dependencies: 
  lints: ^1.0.1
  test: ^1.17.7
