name: astra
description: A simple command-line application.
version: 1.0.0-dev.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies: 
  http2: ^1.0.1

dev_dependencies:
  pedantic: any
