name: astra
description: A simple web server framework based on starlette.
version: 1.0.0-dev.20
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  meta: ^1.3.0
  stack_trace: ^1.10.0

dev_dependencies:
  pedantic: ^1.11.0
