name: astra
description: Astra is a Shelf web server with multi-threaded support and hot reload/restart. Inspired by uvicorn.
version: 1.0.0-dev.117
homepage: https://github.com/ykmnkmi/astra.dart
repository: https://github.com/ykmnkmi/astra.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  astra: astra

dependencies:
  analyzer: ^4.6.0
  args: ^2.3.1
  collection: ^1.16.0
  http: ^0.13.5
  http_parser: ^4.0.1
  logging: ^1.0.2
  meta: ^1.8.0
  path: ^1.8.2
  shelf: ^1.3.2
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0
  vm_service: ^9.3.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  build_version: ^2.1.1
  lints: ^2.0.0
  test: ^1.21.4
