name: astra
description: A simple command-line application.
version: 1.0.0-dev.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies: 
  http2: ^2.0.0-nullsafety.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
