name: astra_repo
description: Astra GitHub repository.
version: 1.0.0+5
publish_to: none

environment:
  sdk: ">=3.8.2 <4.0.0"

dev_dependencies:
  lints: ^6.0.0

workspace:
  - astra
  - astra/example
  - astra_cli
