name: astra
description: A simple web server framework.
version: 1.0.0-dev.10
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  analyzer: ^1.3.0
  http2: ^2.0.0
  meta: ^1.3.0
  stack_trace: ^1.10.0

dev_dependencies:
  pedantic: ^1.10.0
