name: shelf_client
description: HTTP client based on shelf package.
version: 0.0.10
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/shelf_client
repository: https://github.com/ykmnkmi/astra.dart

topics:
  - client
  - http
  - shelf

resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  web: ^1.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
