name: shelf_client
description: HTTP client based on shelf package.
version: 0.0.12
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/shelf_client
repository: https://github.com/ykmnkmi/astra.dart

topics:
  - client
  - http
  - shelf

resolution: workspace

environment:
  sdk: ">=3.8.2 <4.0.0"

dependencies:
  shelf: ^1.4.2
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
