name: shelf_client
description: HTTP client based on shelf package.
version: 0.0.7
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/shelf_client
repository: https://github.com/ykmnkmi/astra.dart

topics:
  - client
  - http
  - shelf

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
