name: example
description: A Shelf based Astra application.
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.8.2 <4.0.0"

dependencies:
  astra: ^1.0.0-dev.166

dev_dependencies:
  lints: ^6.0.0
