name: example
description: A Shelf based Astra application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  astra: ^1.0.0-dev.160

dev_dependencies:
  lints: ^5.0.0
