name: shelf_client_example
description: An absolute bare-bones web app.
version: 1.0.0

resolution: workspace

environment:
  sdk: ">=3.8.2 <4.0.0"

dependencies:
  shelf_client: ^0.0.11
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0
  lints: ^6.0.0
