name: shelf_client_example
description: An absolute bare-bones web app.
version: 1.0.0

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  shelf_client: ^0.0.9
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  lints: ^5.1.0
