name: example
description: A Shelf based Astra application.
version: 1.0.0+2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  astra: ^1.0.0-dev.144

dev_dependencies:
  lints: ^2.1.1
