name: astra
description: >
  A robust, multi-threaded shelf web server adapter designed for high
  performance and concurrent handling of multiple requests.
version: 1.0.0-dev.161
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/astra
repository: https://github.com/ykmnkmi/astra.dart

topics:
  - server
  - shelf

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  http_parser: ^4.1.2
  logging: ^1.3.0
  meta: ^1.16.0
  shelf: ^1.4.2
  shelf_client: ^0.0.9
  stack_trace: ^1.12.1
  stream_channel: ^2.1.4

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.15
