name: astra
description: >
  A robust, multi-threaded shelf web server adapter designed for high
  performance and concurrent handling of multiple requests.
version: 1.0.0-dev.158
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/astra
repository: https://github.com/ykmnkmi/astra.dart

topics:
  - server
  - shelf

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  http_parser: ^4.0.2
  logging: ^1.2.0
  meta: ^1.11.0
  shelf: ^1.4.1
  shelf_client: ^0.0.6
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
