name: astra
description: >
  Astra is Shelf web server adapter and application framework.
version: 1.0.0-dev.149
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/astra
repository: https://github.com/ykmnkmi/astra.dart

topics:
  - server
  - shelf

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  http: ^1.0.0
  http_parser: ^4.0.2
  shelf: ^1.4.0
  stack_trace: ^1.11.0
  stream_channel: ^2.1.2
  vm_service: ^11.9.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
