name: astra_cli
description: >
  The Astra/Shelf CLI tool.
version: 1.0.0-dev.27
homepage: https://github.com/ykmnkmi/astra.dart/tree/master/astra_cli
repository: https://github.com/ykmnkmi/astra.dart
issue_tracker: https://github.com/ykmnkmi/astra.dart/issues

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

executables:
  astra: ^1.0.0-dev.161

dependencies:
  args: ^2.6.0
  astra: ^1.0.0-dev.161
  async: ^2.13.0
  logging: ^1.3.0
  path: ^1.9.1
  pubspec_parse: ^1.5.0
  stack_trace: ^1.12.1
  stream_transform: ^2.1.1
  vm_service: ^15.0.0
  watcher: ^1.1.1

dev_dependencies:
  lints: ^5.1.0
