name: astra_cli
description: >
  The Astra/Shelf CLI with multi-threaded and hot reload/restart support.
version: 1.0.0-dev.2
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

executables:
  astra: astra

dependencies:
  args: ^2.3.1
  astra: ^1.0.0-dev.130
  analyzer: ^5.2.0
  path: ^1.8.2
  stream_transform: ^2.1.0
  yaml: ^3.1.1
  vm_service: ^9.4.0

dev_dependencies:
  lints: ^2.0.1
