name: astra_cli
description: >
  The Astra/Shelf CLI tool.
version: 1.0.0-dev.6
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  astra: ^1.0.0-dev.130
  async: ^2.10.0
  analyzer: ^5.2.0
  path: ^1.8.2
  pubspec: ^2.3.0
  stream_transform: ^2.1.0
  vm_service: ^9.4.0
  watcher: ^1.0.2

dev_dependencies:
  lints: ^2.0.1
